#!/bin/sh

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'


date
echo "${RED} \n\n\n Baixando pacote de instalacao do WPS \n\n ${SET}"


case $(uname -m) in
x86_64)
	wget http://kdl.cc.ksosoft.com/wps-community/download/8372/wps-office_11.1.0.8372_amd64.deb --no-check-certificate -O wps-office.deb


    ;;
i*86)
	wget http://kdl.cc.ksosoft.com/wps-community/download/8372/wps-office_11.1.0.8372_i386.deb --no-check-certificate -O wps-office.deb
    ;;
*)
    BITS=?
    ;;
esac




wget http://kdl.cc.ksosoft.com/wps-community/download/fonts/wps-office-fonts_1.0_all.deb -O web-office-fonts.deb



echo "${RED} Instalando o WPS ${SET}"
sudo dpkg -i wps-office*.deb

sudo apt-get install -f

sudo dpkg -i /Instalacao/WPS/wps-office-language-pt-br-osistematico-4.0.deb
