#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'

date
echo "${RED}\n\n\n Adicionando os Repositorios necessarios \n\n${SET}"
sudo add-apt-repository -y "deb http://archive.canonical.com/ oneiric partner" -y
sudo add-apt-repository -y ppa:webupd8team/java -y
sudo add-apt-repository -y ppa:noobslab/icons -y
sudo add-apt-repository -y ppa:dirk-computer42/c42-backport -y
sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/ -y
sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main' -y
sudo add-apt-repository ppa:wine/wine-builds -y
sudo add-apt-repository ppa:jonathonf/firefox-esr -y

sudo dpkg --add-architecture i386
sudo apt install ia32-libs libc6:i386 libncurses5:i386 libstdc++6:i386 multiarch-support gcc-multilib lib32z1 libgtk2.0-0:i386 libglu1-mesa:i386 libxmu6:i386 libidn11:i386 libusb-0.1-4:i386


sudo apt-get update
sudo apt-get install gedit -y
sudo apt-get install exfat-fuse exfat-utils -y --force-yes
sudo apt-get install dconf* -y


