#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'

date
echo "${RED}\n\n\n Instalando themes \n\n${SET}"

#sudo apt-get install win-icons -y
sudo apt-get install victory-icon-theme
sudo cp -vR /Instalacao/Temas/Cinnamon/Themes/* /usr/share/themes
sudo chmod 777 -R /usr/share/themes/*
sudo cp -vR /Instalacao/Temas/Cinnamon/Icons/Win10 /usr/share/icons
sudo chmod 777 -R /usr/share/icons/Win10
wget https://launchpad.net/~noobslab/+archive/ubuntu/themes/+files/windos-10-themes_1.0~yakkety~NoobsLab.com_all.deb -O windos-10-theme.deb

sudo dpkg -i windos-10-theme.deb


sudo apt-get install dconf-* -y



