#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'

date
echo "${RED}\n\n\n Instalando o Chrome \n\n${SET}"
sleep 3
echo "${RED}\n\n\n Libs \n\n${SET}"
sudo apt-get install -y libcurl3 libpango1.0-0 
sleep 3

echo "${RED}\n\n\n Chrome \n\n${SET}"
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
sudo apt-get update 
sudo apt-get install google-chrome-stable -y --allow-unauthenticated
sudo apt-get install -f 
sudo apt install --only-upgrade libnss3



google-chrome &


