#!/bin/sh

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'


date
echo "${RED} \n\n\n Baixando pacote de instalacao do Java8 \n\n ${SET}"

sudo apt remove icedtea-*

wget https://javadl.oracle.com/webapps/download/AutoDL?BundleId=238719_478a62b7d4e34b78b671c754eaaf38ab -O java.tar.gz

sudo mkdir -p /usr/lib/jvm
sudo tar zxvf java.tar.gz -C /usr/lib/jvm/
sudo mv /usr/lib/jvm/jre* /usr/lib/jvm/jre

sudo ln -s /usr/lib/jvm/jre /usr/lib/jvm/java-oracle

sudo cp -a /etc/profile /etc/profile.original

sudo sed -i '3i JAVA_HOME=/usr/lib/jvm/java-oracle/ \n PATH=$JAVA_HOME/bin:$PATH export PATH JAVA_HOME \n CLASSPATH=$JAVA_HOME/lib/tools.jar \n CLASSPATH=.:$CLASSPATH \n export  JAVA_HOME  PATH  CLASSPATH \n' /etc/profile


mkdir -p $HOME/.java/deployment/security
cp -v /Instalacao/Java/exception.sites $HOME/.java/deployment/security/exception.sites
mkdir -p $HOME/.local/share/applications/
cp -v /Instalacao/Java/Sitef.desktop ~/.local/share/applications/


echo "${RED}\n\n\n Para o Java Funcionar é necessario reiniciar o computador.... ${SET}"

sleep 3







