#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'

date
echo "${RED}\n\n\n Favoritos chrome e firefox \n\n${SET}"

echo "apagando pastas se existirem.."
cd /Instalacao/Internet/
sudo rm -R /Instalacao/Internet/Firefox.cfg /Instalacao/Internet/Chrome.cfg /Instalacao/Internet/chromium.cfg
tar -zxvf Firefox.cfg.tar.gz
tar -zxvf Chrome.cfg.tar.gz
tar -zxvf chromium.cfg.tar.gz

echo "\n\n\n Criando favoritos do FireFox"
firefox-esr &
sleep 5
killall -9 firefox-esr
sleep 5
cp -vrf /Instalacao/Internet/Firefox.cfg/* $HOME/.mozilla/firefox/*.default/


echo "\n\n\n Criando favoritos do Chrome"
mkdir $HOME/.config/google-chrome/Default/
sleep 5
cp -vrf /Instalacao/Internet/Chrome.cfg/* $HOME/.config/google-chrome/Default/



echo "\n\n\n Criando favoritos do Chromium"
mkdir $HOME/.config/chromium/Default/
sleep 5
cp -vrf /Instalacao/Internet/chromium.cfg/* $HOME/.config/chromium/Default/
