#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'

date
echo "${RED}\n\n\n Biometria \n\n${SET}"
sleep 3
echo "${RED}\n\n\n Copiando arquivos\n\n${SET}"
sudo mkdir -p /Zanthus/Zeus
sudo chmod -R 777 /Zanthus/Zeus
cd /Instalacao/Biometria
sudo cp -vr ld.so.conf.d /etc/
cp -vr lib* ctbiom /Zanthus/Zeus/
cp -v Biometria.sh /zanthus/Zeus/ctbiom
sleep 3
echo "${RED}\n\n\n ldconfig \n\n${SET}"

cd /etc/ld.so.conf.d
sudo ldconfig
cd /Zanthus/Zeus/lib
sudo ldconfig
cd /Zanthus/Zeus/lib_ubu
sudo ldconfig
cd /Zanthus/Zeus/lib_co5
sudo ldconfig


sudo dpkg --print-architecture 

sudo dpkg --print-foreign-architectures

sleep 3
echo "${RED}\n\n\n Auto Start  \n\n${SET}"

sudo touch /etc/xdg/autostart/biometriacxc.desktop
sudo chmod 777 /etc/xdg/autostart/biometriacxc.desktop
sudo echo "[Desktop Entry]
Name=Inicia Biometria
Comment=Inicia serviço da biometria
Keywords=biometria
NoDisplay=true
Exec=sudo /Zanthus/Zeus/ctbiom/./lnx_ctbiom.xz
OnlyShowIn=GNOME;LXDE;Unity;MATE;XFCE;
Terminal=false
Type=Application
X-GNOME-Autostart-Phase=Applications
X-GNOME-AutoRestart=true
X-GNOME-UsesNotifications=true
X-Ubuntu-Gettext-Domain=biometria" > /etc/xdg/autostart/biometriacxc.desktop

sleep 3
echo "${RED}\n\n\n Auto Start  \n\n${SET}"

echo "${GREEN}\n\n\n Edite o sudoers (/etc/sudoers) MUITO CUIDADO COM A EDICAO DESTE ARQUIVO!!! QUALQUER ERRO, DEIXARA O SO INABILITADO!!!!!!

Após a palavra 'NOPASSWORD' de cada usuario, inserir a linha abaixo ao final da linha (voce devera colocar a virgula ',' antes de colar ou escrever a linha abaixo):

/Zanthus/Zeus/ctbiom/Biometria.sh,/Zanthus/Zeus/ctbiom/lnx_ctbiom.xz

Exemplo de como ficara a edicao: 
${RED}
adming   ALL=(ALL) ALL, NOPASSWD: /bin/mount,/sbin/shutdown,/sbin/poweroff,/sbin/reboot,/bin/bash,/bin/sh,${GREEN}/Zanthus/Zeus/ctbiom/Biometria.sh,/Zanthus/Zeus/ctbiom/lnx_ctbiom.xz
${SET}"


sudo nano /etc/sudoers
