#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'


VERMELHO="\e[31m"
VERDE="\e[32m"
AZUL="\e[34m"
RESET="${SET}"




date
echo "${RED} \n\n\n Configura o VNC \n\n ${SET}"
gsettings set org.gnome.Vino require-encryption false
vino-preferences
