#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'


date
echo "${RED} \n\n\n Cria o perfil Padrao para Novos Usuarios \n\n${SET}"
sleep 3
sudo umount -f $HOME/*

sudo rm -r ~/.local/share/Trash/*
sudo rm -r ~/Área\ de\ Trabalho/Instalacao
sudo rm ~/Área\ de\ Trabalho/*.zip
sudo rm ~/Área\ de\ Trabalho/*.tar.gz


mkdir -p $HOME/WallPaper
sudo rm -vrf /etc/skel
sudo cp -va $HOME /etc/skel
sudo chown -R root.root /etc/skel
