#!/bin/bash

RKGRAY='\033[1;30m'
eRED='\033[0;31;160m'
RED='\033[37;41m'
LIGHTRED='\033[1;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
LIGHTPURPLE='\033[1;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
SET='\033[0m'

date
echo "${RED}\n\n\n Instalando o PlayonLinux \n\n${SET}"

sudo apt remove wine wine1.8 wine-stable libwine* fonts-wine* && sudo apt autoremove -y
sudo dpkg --add-architecture i386
wget -nc https://dl.winehq.org/wine-builds/Release.key
sudo apt-key add Release.key
sudo apt-get install --install-recommends winehq-stable -y
sudo aptitude install winehq-stable -y
uname -m


sudo apt-get update
sudo apt-get install --install-recommends winehq-devel -y
sudo apt-get install flex bison qt4-qmake gcc-multilib g++-multilib lib32z1-dev lib32bz2-dev libx11-dev libfreetype6-dev:i386 -y


wget https://dl.winehq.org/wine/source/2.x/wine-2.18.tar.xz -O wine.tar.xz
tar Jxf wine.tar.xz
cd wine-*
./configure
uname -m
./configure --enable-win64
cd tools
./wineinstall

sudo mkdir -p $HOME/.cache/wine
sudo chmod 777 $HOME/.cache/wine
cd /Instalacao
cp -v wine_gecko-2.47-x86.msi wine-mono-4.7.3.msi $HOME/.cache/wine

sudo apt-get install playonlinux xterm -y

